### PR TITLE
Lesson 2 Worksheet Update - closes #12

### LINKED ISSUE #12: Lesson 2 missing thing-client.py ?
Looking at https://www.raspberrypi.org/learning/networking-lessons/lesson-2/worksheet/ it has the source-code for `thing-server.py` but no source-code (or download link) for the `thing-client.py` script?
(Or is it included elsewhere and I simply overlooked it?)

Elsewhere on that same page it also says "The server machine is connected to a button. It monitors data from the client machine, and when it receives a '?' character..." but the `thing-server.py` script actually looks like it listens for _any_ character that isn't a carriage-return or newline?

### PR DESCRIPTION
**Pull request by jonwitts**
Update worksheet to use GPIOZero, updated Fritzing wiring diagrams, added the missing thing-client.py code and changed to use Python3.

### CODE REVIEW

**Comment by jonwitts** [comment]
close #12

**Comment by lawsie** [comment]
I've attached two of the new style diagrams - we don't use the fritzing ones any more (the ones still left are on resources that haven't been updated yet). The diagram I found of the button, the button is on pin 4 not pin 10. Please could you add these in to your PR instead of the others? I also fixed a formatting issue (github accepts tabs as 4 spaces and it was 3 spaces for some of the code, meaning the markdown later on broke!) :) Thanks very much for this update.

led-gpio17
button-gpio4

**Comment by jonwitts** [comment]
Yep, will get those added. What are you using for wiring diagrams now? Is it something I can install too?

**Comment by jonwitts** [comment]
OK, I think they are all ready to go now :-D

**Pull request merged**
